language: node_js

deploy:
  provider: heroku
  api_key:
    secure: "53711ff6-0487-4f5f-b742-544d89205040"

node_js: 
  - node

cache: 
  directories: 
    - "node_modules"

after_success: 
   - npm run coverage
