// import './testFiles/app.spec';
import './testFiles/helpers.spec';
import './testFiles/login.spec';
import './testFiles/signUp.spec';
import './testFiles/redFlags.spec';
import './testFiles/postRedFlag.spec';
import './testFiles/postIntervention.spec';
import './testFiles/updateComment.spec';
import './testFiles/updateLocation.spec';
import './testFiles/updateStatus.spec';
import './testFiles/updateImage.spec';
import './testFiles/getRedFlags.spec';
import './testFiles/deleteRedflag.spec';
import './testFiles/deleteIncident.spec';
